CREATE TABLE DEPARTAMENTO
( NR INTEGER PRIMARY KEY,
NOME VARCHAR(20),
ID_REG INTEGER REFERENCES REGIAO(NR))

SELECT * FROM REGIAO
SELECT * FROM DEPARTAMENTO

INSERT INTO DEPARTAMENTO VALUES (1,'D1', 1)
INSERT INTO DEPARTAMENTO VALUES (2,'D2',2)
INSERT INTO DEPARTAMENTO VALUES (3,'D3',3)
